name: Windows with Nuitka

on:
  push:
    paths:
      - 'install_windows.py'
      - '.github/workflows/windows_nuitka.yml'
  pull_request:
    paths:
      - 'install_windows.py'
      - '.github/workflows/windows_nuitka.yml'
  workflow_dispatch:

jobs:
  install_and_test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9  # 指定 Python 3 版本

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build install_windows_nuitka.exe
      uses: Nuitka/Nuitka-Action@main
      with:
        nuitka-version: main
        script-name: install_windows.py
        standalone: true
        onefile: true
        windows-uac-admin: true
        enable-plugins: tk-inter
        output-file: install_windows_nuitka.exe

    - name: Upload install_windows_nuitka.exe
      uses: actions/upload-artifact@v4
      with:
        name: install_windows_nuitka
        path: build/install_windows_nuitka.exe

    - name: Download and Install QQ Software
      run: |
        # Download QQ software
        python3 get_qqnt.py Windowsx64
        # Install QQ silently
        Start-Process -FilePath QQInstaller.exe -ArgumentList '/S' -Wait

    - name: Run install_windows_nuitka.exe
      run: |
        .\build\install_windows_nuitka.exe

    - name: Check QQNT Process
      shell: pwsh
      run: |
        Start-Process -FilePath "C:\Program Files\Tencent\QQNT\QQ.exe" -ArgumentList '--enable-logging' -NoNewWindow
        Start-Sleep -Seconds 5  # 等待 5 秒
        Get-Process -Name "QQ"  # 检查 QQ 进程是否在运行

    - name: Check if LiteLoader plugins folder exists
      run: |
        if (Test-Path "C:\Program Files\Tencent\QQNT\resources\app\LiteLoaderQQNT\data") {
          Write-Host "LiteLoader folder found. Test passed."
        } else {
          Write-Host "LiteLoader folder not found. Test failed."
          exit 1
        }
